# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HandyAccess' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HandyAccess
  pod 'SnapKit'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Mapbox-iOS-SDK', '~> 3.3.7'
  pod 'SideMenu'
  

end
